###

GET http://localhost:8080/movies/all

###

POST http://localhost:8080/movies/
Content-Type: application/json

{
  "title": "Titanic",
  "genre": "Romance",
  "duration": 195,
  "rating": 8.8,
  "releaseYear":1997
}

###

PUT http://localhost:8080/movies/update/Titanic
Content-Type: application/json

{
  "title": "Titanic",
  "genre": "Romance",
  "duration": 210,
  "rating": 9.0,
  "releaseYear": 1997
}

###
DELETE http://localhost:8080/movies/Titanic

###
DELETE http://localhost:8080/movies/


###

GET http://localhost:8080/showtimes/all
###

GET http://localhost:8080/showtimes/102

###

POST http://localhost:8080/showtimes/
Content-Type: application/json

{
  "movieId": 402,
  "price":20.5,
  "theater": "Small Theater",
  "startTime": "2025-02-18T11:47:46.125405Z",
  "endTime": "2025-02-18T14:47:46.125405Z" 
}

###

PUT http://localhost:8080/showtimes/update/102
Content-Type: application/json

{
  "movieId": 302,
  "price":50.5,
  "theater": "Small Theater",
  "startTime": "2025-02-14T11:47:46.125405Z",
  "endTime": "2025-02-14T14:47:46.125405Z" 
}

###

DELETE http://localhost:8080/showtimes/102

###

DELETE http://localhost:8080/showtimes/