###

GET http://localhost:8080/movies/all

###

POST http://localhost:8080/movies/
Content-Type: application/json

{
  "title": "Avatar",
  "genre": "Action",
  "duration": 195,
  "rating": 8.8,
  "releaseYear":2009
}

###

PUT http://localhost:8080/movies/update/Titanic
Content-Type: application/json

{
  "title": "Titanic",
  "genre": "Romance",
  "duration": 220,
  "rating": 9.0,
  "releaseYear": 1997
}

###
DELETE http://localhost:8080/movies/Titanic

###
DELETE http://localhost:8080/movies/


###

GET http://localhost:8080/showtimes/all
###

GET http://localhost:8080/showtimes/403

###

POST http://localhost:8080/showtimes/
Content-Type: application/json

{
  "movieId": 652,
  "price":20.5,
  "theater": "small Theater",
  "startTime": "2025-02-20T14:47:47.125405Z",
  "endTime": "2025-02-20T17:47:46.125405Z" 
}

###

PUT http://localhost:8080/showtimes/update/504
Content-Type: application/json

{
  "movieId": 652,
  "price": 50.5,
  "theater": "small Theater",
  "startTime": "2025-02-20T17:47:48.125405Z",
  "endTime": "2025-02-20T21:47:46.125405Z" 
}

###

DELETE http://localhost:8080/showtimes/403

###

DELETE http://localhost:8080/showtimes/

###

POST http://localhost:8080/bookings/
Content-Type: application/json

{
  "showtimeId": 452,
  "seatNumber": 10,
  "userId": "84438967-f68f-4fa0-b620-0f08217e76af"
}

###
GET http://localhost:8080/bookings/