###

GET http://localhost:8080/movies/all

###

POST http://localhost:8080/movies/
Content-Type: application/json

{
  "title": "bbb",
  "genre": "Crime",
  "duration": 175,
  "rating": 9.2,
  "releaseYear": 1972
}

###

PUT http://localhost:8080/movies/update/bbb
Content-Type: application/json

{
  "title": "AAAAAAAA",
  "genre": "Crime",
  "duration": 175,
  "rating": 9.2,
  "releaseYear": 1972
}

###
DELETE http://localhost:8080/movies/AAAAAAAA

###
DELETE http://localhost:8080/movies/


###

GET http://localhost:8080/showtimes/all
###

GET http://localhost:8080/showtimes/2

###

POST http://localhost:8080/showtimes/
Content-Type: application/json

{
  "movieId": 210,
  "price":20.5,
  "theater": "Sample Theater",
  "startTime": "2025-02-14T11:47:46.125405Z",
  "endTime": "2025-02-14T14:47:46.125405Z" 
}